server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/dqit-cloud
    # 开发环境方便日志输出
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      test-while-idle: false
      validation-query: "select 1"
common:
  swagger:
    enable: true