FROM openjdk:8-jre

MAINTAINER mr_hqing@163.com

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /spring-cloud-demo

EXPOSE 80

ADD ./target/system-gateway-0.0.1-SNAPSHOT.jar ./

CMD ["java","-Djava.security.egd=file:/dev/./urandom", "-Duser.timezone=Asia/Shanghai", "-jar system-gateway-0.0.1-SNAPSHOT.jar"]
